### ISSUE TITLE
Dacco XML files

### ISSUE THREAD

**Issue by pereorga** [cpina/qdacco#1]
Hola,

On es poden baixar els fitxers XML?

Saps si s'ha convertit mai el diccionari a DICTD, StarDict o a altres formats?

Salutacions

**Comment by cpina** [comment]
Hola Pere,

Els diccionaris es poden baixar des del projecte de Sourceforge:
https://sourceforge.net/projects/dacco/files/Dacco/0.9/

No veig noves versions ni cap enllaç a la Web de Dacco (http://www.catalandictionary.org)

També es poden trobar als fitxers de Debian, com ara aquí: https://packages.debian.org/jessie/dacco-common i el fitxer amb els XML seria a dacco_0.9+20071227.orig.tar.gz (http://http.debian.net/debian/pool/main/d/dacco/dacco_0.9+20071227.orig.tar.gz)

Que jo sàpiga no han estat mai convertits a DICTD o StarDict.

La web de CatalanDictionary sembla força "morta", el qdacco vaig fer una versió que funciona amb Qt5 i l'intenció és que quan Debian es descongeli hi entri...

Si vols o necessites res més avisa!

**Comment by pereorga** [comment]
Hola Carles,

Havia trobat els fitxers de sourceforge, però com que a la web posa que es va actualitzar per última vegada el 2014, havia suposat que havien d'estar més actualitzats en algun altre lloc (els fitxers de Sourceforge es van actualitzar per última vegada el 2005)

Provaré de contactar amb ells i si em contesten et diré alguna cosa.

Gràcies!

**Comment by cpina** [comment]
> Hola Carles,
> 
> Havia trobat els fitxers de sourceforge, però com que a la web posa que es va actualitzar per última vegada el 2014, havia suposat que havien d'estar més actualitzats en algun altre lloc (els fitxers de Sourceforge es van actualitzar per última vegada el 2005)
> 
> Provaré de contactar amb ells i si em contesten et diré alguna cosa.
> 
> Gràcies!

Hola Pere,

No recordava gens els nostres missatges fa dos anys. Ahir vaig posar l'última versió que conec dels fitxers DACCO aquí per evitar que es perdin:
https://github.com/cpina/dacco

Si saps res més digue-ho aquí. Ja sé que fa dos anys d'això :-)
