### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by lepalom** [cpina/qdacco#2]
Packaging qdacco, lintian complains in:

qdacco: spelling-error-in-binary usr/bin/qdacco everytime every time
N:
I: spelling-error-in-binary
N:
N:   Lintian found a spelling error in the given binary. Lintian has a list
N:   of common misspellings that it looks for. It does not have a
N:   dictionary like a spelling checker does.
N:   
N:   If the string containing the spelling error is translated with the
N:   help of gettext or a similar tool, please fix the error in the
N:   translations as well as the English text to avoid making the
N:   translations fuzzy. With gettext, for example, this means you should
N:   also fix the spelling mistake in the corresponding msgids in the *.po
N:   files.
N:

**Comment by cpina** [comment]
Thanks! - fixed via #3 - I'll also improve some other help strings soon.
